### ISSUE TITLE
panic on the server when sync client timeouts

### ISSUE THREAD

**Issue by cendhu** [IBM-Blockchain/bcdb-server#106]
When the client waiting for a sync commit times out, the server panics. The following is the stack trace
```

panic: send on closed channel

goroutine 138 [running]:
github.com/IBM-Blockchain/bcdb-server/internal/bcdb.(*promise).done(...)
	/root/github.com/IBM-Blockchain/bcdb-server/internal/bcdb/transaction_processor.go:327
github.com/IBM-Blockchain/bcdb-server/internal/bcdb.(*pendingTxs).removeAndSendReceipt(0xc0000cc760, 0xc0184b0000, 0x1f4, 0x200, 0xc03b87ce10)
	/root/github.com/IBM-Blockchain/bcdb-server/internal/bcdb/transaction_processor.go:272 +0x1b2
github.com/IBM-Blockchain/bcdb-server/internal/bcdb.(*transactionProcessor).PostBlockCommitProcessing(0xc0003b2850, 0xc0360bc280, 0xc80f43, 0x25)
	/root/github.com/IBM-Blockchain/bcdb-server/internal/bcdb/transaction_processor.go:226 +0x27a
github.com/IBM-Blockchain/bcdb-server/internal/blockprocessor.(*blockCommitListeners).invoke(0xc0003a1140, 0xc0360bc280, 0x0, 0x0)
	/root/github.com/IBM-Blockchain/bcdb-server/internal/blockprocessor/processor.go:282 +0x226
github.com/IBM-Blockchain/bcdb-server/internal/blockprocessor.(*BlockProcessor).Start(0xc00030c370)
	/root/github.com/IBM-Blockchain/bcdb-server/internal/blockprocessor/processor.go:136 +0x6d0
created by github.com/IBM-Blockchain/bcdb-server/internal/bcdb.newTransactionProcessor
	/root/github.com/IBM-Blockchain/bcdb-server/internal/bcdb/transaction_processor.go:119 +0x725
```

**Comment by tock-ibm** [comment]
This is caused because the receiver closes the channel (in wait), rather then sender (in done). This will be fixed during the work on refactoring the pending tx queue.

**Comment by C0rWin** [comment]
I have also encountered this, and I think that, in general, there is should be a 500 HTTP Internal Error response in most of the cases instead of letting the server to panic.
