### ISSUE TITLE
flaky test - block replicator

### ISSUE THREAD

**Issue by cendhu** [IBM-Blockchain/bcdb-server#127]
```
2021-07-23T09:01:45.366Z	DEBUG	replication/blockreplicator.go:156	Submit of block [506] refused, not a leader: not a leader, leader is: 0	{"nodeID": "node1", "raftID": 1}
1028
2021-07-23T09:01:45.367Z	DEBUG	replication/storage.go:63	No snapshot found at /tmp/replication-test964472854/snap	{"nodeID": "node1", "raftID": 1}
1029
2021-07-23T09:01:45.367Z	INFO	replication/storage.go:160	No WAL data found, creating new WAL at path '/tmp/replication-test964472854/wal'	{"nodeID": "node1", "raftID": 1}
1030
panic: Fail in goroutine after TestBlockReplicator_Submit/normal_flow:_blocked_submit has completed
1031

1032
goroutine 286 [running]:
1033
testing.(*common).Fail(0xc0002d0a80)
1034
	/opt/hostedtoolcache/go/1.16.6/x64/src/testing/testing.go:697 +0x125
1035
testing.(*common).Errorf(0xc0002d0a80, 0xb1bbef, 0x3, 0xc0002f5cd0, 0x1, 0x1)
1036
	/opt/hostedtoolcache/go/1.16.6/x64/src/testing/testing.go:803 +0x93
1037
github.com/stretchr/testify/assert.Fail(0xbde9e0, 0xc0002d0a80, 0xc00001f110, 0x63, 0x0, 0x0, 0x0, 0x9d2d01)
1038
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.6.1/assert/assertions.go:262 +0x2fb
1039
github.com/stretchr/testify/assert.EqualError(0xbde9e0, 0xc0002d0a80, 0xbddd60, 0xc00002df48, 0xb257ab, 0x17, 0x0, 0x0, 0x0, 0xc0002cc248)
1040
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.6.1/assert/assertions.go:1371 +0x209
1041
github.com/stretchr/testify/require.EqualError(0xbe41f8, 0xc0002d0a80, 0xbddd60, 0xc00002df48, 0xb257ab, 0x17, 0x0, 0x0, 0x0)
1042
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.6.1/require/require.go:177 +0xeb
1043
github.com/IBM-Blockchain/bcdb-server/internal/replication_test.TestBlockReplicator_Submit.func3.2()
1044
	/home/runner/work/bcdb-server/bcdb-server/internal/replication/blockreplicator_test.go:250 +0x1cb
1045
created by github.com/IBM-Blockchain/bcdb-server/internal/replication_test.TestBlockReplicator_Submit.func3
1046
	/home/runner/work/bcdb-server/bcdb-server/internal/replication/blockreplicator_test.go:257 +0x255
1047
FAIL	github.com/IBM-Blockchain/bcdb-server/internal/replication	18.310s
```

**Comment by tock-ibm** [comment]
When a blockreplicaor is closed, Submit can result in either of two errors:
    - closed error, or
    - not-a-leader error;
depending on the scheduling of the threads.

The test was changed to reflect that.
